name: Issue Notifier

on:
  workflow_dispatch:
  schedule:
    - cron:  '*/5 * * * *'

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
      
    - name: Install dependencies
      run: pip install requests pyyaml logging python-dateutil pytz
      
    - name: Run script
      run: python scripts/notify.py
      env:
        SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
